/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.View {
    export class LoadingUI extends Scene {
        public static  uiView:any ={"type":"Scene","props":{"width":1920,"top":0,"right":0,"left":0,"height":1080,"bottom":0},"compId":2,"child":[{"type":"Clip","props":{"y":0,"x":0,"skin":"Loading/1_0001_图层-3.jpg","name":"Bg"},"compId":6,"child":[{"type":"Clip","props":{"width":1920,"skin":"Loading/图层 1.png","pivotY":22,"name":"processBar","left":0,"height":22,"bottom":98},"compId":5}]},{"type":"Script","props":{"y":0,"x":0,"runtime":"View/LoadingView/LoadingView.ts"},"compId":7}],"loadList":["Loading/1_0001_图层-3.jpg","Loading/图层 1.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(LoadingUI.uiView);
        }
    }
    REG("ui.View.LoadingUI",LoadingUI);
}