/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameMgr from "./Mgr/GameMgr"
import TwinkleSprite from "./View/TwinkleSprite"
import ClickGetPrize from "./View/ClickGetPrize/ClickGetPrize"
import LoadingView from "./View/LoadingView/LoadingView"
import TipsView from "./View/TipsView/TipsView"
import LoopAdBox from "./ShareAd/View/LoopAdBox"
import HorizontalLoopAdView from "./ShareAd/View/HorizontalLoopAdView"
import BannerAdView from "./ShareAd/View/BannerAdView"
import UniversalBottomZone from "./View/Common/UniversalBottomZone"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="GameMain.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("Mgr/GameMgr.ts",GameMgr);
        reg("View/TwinkleSprite.ts",TwinkleSprite);
        reg("View/ClickGetPrize/ClickGetPrize.ts",ClickGetPrize);
        reg("View/LoadingView/LoadingView.ts",LoadingView);
        reg("View/TipsView/TipsView.ts",TipsView);
        reg("ShareAd/View/LoopAdBox.ts",LoopAdBox);
        reg("ShareAd/View/HorizontalLoopAdView.ts",HorizontalLoopAdView);
        reg("ShareAd/View/BannerAdView.ts",BannerAdView);
        reg("View/Common/UniversalBottomZone.ts",UniversalBottomZone);
    }
}
GameConfig.init();